apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
    backstage.io/kubernetes-id: {{ .Values.name }}
  name: {{ .Values.name }}-jbang-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        backstage.io/kubernetes-id: {{ .Values.name }}
    spec:
      containers:
      - name: integration
        image: apache/camel-jbang:4.16.0
        args: ["run", "/integrations/integration.yaml"]
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /integrations
          name: camel-conf
      volumes:
      - name: camel-conf
        configMap: 
          name: {{ .Values.configmap }}
          items:
            - key: integration.yaml
              path: integration.yaml