apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaoto-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KaotoIO/kaoto-operator/
    targetRevision: HEAD
    path: config/default

  destination:
    server: https://kubernetes.default.svc
    namespace: camel-k
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true