apiVersion: v2
appVersion: 2.8.0
description: A lightweight integration platform, born on Kubernetes, with serverless
  superpowers
home: https://camel.apache.org/camel-k/latest/
icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
keywords:
- serverless
- integration
- patterns
maintainers:
- email: pcongiusti@apache.org
  name: pcongiusti
- email: acosentino@apache.org
  name: acosentino
name: camel-k
sources:
- https://github.com/apache/camel-k
- https://github.com/apache/camel-k-runtime
- https://github.com/apache/camel-quarkus
- https://github.com/apache/camel
type: application
version: 2.8.0
