apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: my-simple-http-service

helmChartInflationGenerator:
  - chartRepoUrl: https://wiremock.github.io/helm-charts
    chartName: wiremock
    chartVersion: 1.9.1
    releaseName: my-simple-http-service
    values: values.yaml

# resources:
#   - ingress.yaml
#   - k8s-rbac.yaml
#   - users-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true
