apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - camel-karavan.yaml
  - cert-manager.yaml
  - kyverno.yaml
  - kyverno-rbac.yaml
  - prometheus.yaml
  - rabbitmq.yaml
  - strimzi-operator.yaml
  - kafka-cluster.yaml
  - http-ingress.yaml
