# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: catalog-component-camel-k-mesh-{{.Values.name}}
#   namespace: backstage
# data:
#   catalog-component-camel-k-mesh-{{.Values.name}}.yaml: |
#     apiVersion: backstage.io/v1alpha1
#     kind: Domain
#     metadata:
#       name: {{.Values.name}}
#       description: Everything about {{.Values.name}}
#     spec:
#       owner: apim
    