apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: camel-k-mesh-{{.Values.name}}
  name: camel-k-operator-binding
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: camel-k-mesh
roleRef:
  kind: Role
  name: camel-k-operator
  apiGroup: rbac.authorization.k8s.io
