# apiVersion: camel.apache.org/v1
# kind: IntegrationPlatform
# metadata:
#   labels:
#     app: camel-k-mesh-{{.Values.name}}
#   name: integration-platform
#   namespace: camel-k-mesh-{{.Values.name}}
# spec:
#   build:
#     registry:
#       address: ghcr.io
#       organization: craigedmunds
#       insecure: true
#       secret: ghcr-classic