apiVersion: v1
kind: Namespace
metadata:
  labels:
    
    # These two labels are currently used by kyverno to add the rabbit secret
    apim/service.type: mesh-lob
    apim/deps.rabbitmq: 'true'
  name: camel-k-mesh-{{.Values.name}}