apiVersion: v1
kind: Secret
metadata:
  labels:
    app: camel-k-mesh-{{.Values.name}}
  name: camel-k-mesh-default-user
  namespace: camel-k-mesh-{{.Values.name}}
type: Opaque
data:
  username: {{ (lookup "v1" "Secret" "camel-k-mesh" "camel-k-mesh-default-user").data.username | b64enc }}
  password: {{ (lookup "v1" "Secret" "camel-k-mesh" "camel-k-mesh-default-user").data.password | b64enc }}
