apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    repo: argocd-eda
spec:
  project: eventing
  source:
    repoURL: https://github.com/nivreddy14/event-mesh.git
    targetRevision: HEAD
    path: kustomize/backstage
      
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
