
helmChartInflationGenerator:
  - chartHome: ../../../../helm
    chartName: jbang-camel-integration
    releaseName: camel-k-mesh-producer-demo-user-service
    values: values.yaml

resources:
- confluent-user-topic.yaml
- jbang-configmap.yaml
