apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: lob-demo-user-service-sample-usercreated
  namespace: camel-k-mesh
spec:
  name: q.demo.userservice.sample.usercreated # name of the queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: camel-k-mesh

---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: lob-demo-user-service-sample-usercreated-binding
  namespace: camel-k-mesh
spec:
  source: ex.demo.userservice.usercreated # an existing exchange (the rabbit mq internal name)
  destination: q.demo.userservice.sample.usercreated # an existing queue (the rabbit mq internal name)
  destinationType: queue # can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: camel-k-mesh