apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-k-mesh-consumer-{{.Values.name}}
    backstage.io/kubernetes-id: camel-k-mesh-consumer-{{.Values.name}}
  name: camel-k-mesh-consumer-{{.Values.name}}-jbang-deployment
  namespace: camel-k-mesh-consumer-{{.Values.name}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: camel-k-mesh-consumer-{{.Values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: camel-k-mesh-consumer-{{.Values.name}}
        backstage.io/kubernetes-id: camel-k-mesh-consumer-{{.Values.name}}
    spec:
      containers:
      - name: integration
        image: apache/camel-jbang:4.16.0
        args: ["run", "/integrations/integration.yaml"]
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /integrations
          name: camel-conf
      volumes:
      - name: camel-conf
        configMap: 
          name: camel-k-mesh-consumer-{{.Values.name}}-config
          items:
            - key: integration.yaml
              path: integration.yaml